<a href="https://colab.research.google.com/github/zackhalepoto/Data_Science_Projects/blob/main/Amazon_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer


In [ ]:
df=pd.read_excel("Amazon_scrapping.xlsx")
df.head()

title  seller  \
0              Apple TV Siri Remote (2nd Generation)     NaN   
1  Outdoor Bluetooth Speaker with Light, Gift for...     NaN   
2  Victrola Vintage 3-Speed Bluetooth Portable Su...     NaN   
3  Sonos Beam (Gen 2). The Compact Smart soundbar...     NaN   
4  Philips FX10 Bluetooth Stereo System for Home ...     NaN   

   seller/averageRating       seller/id seller/name  seller/reviewsCount  \
0                   NaN   ALAQLAKJ574UN        6ave                  NaN   
1                   NaN  A2J27EKX3JZ2SO    KuccHero                  NaN   
2                   NaN             NaN         NaN                  NaN   
3                   NaN   AFVUN7WVFH1YR       PetzX                  NaN   
4                   NaN   A6EGA15UEFYEQ   PHOTOTECH                  NaN   

                                          seller/url  price price/currency  \
0  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
1  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
2                                                NaN    NaN              $   
3  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
4  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   

   price/value  ... variantAsins/21 variantAsins/22 variantAsins/23  \
0        54.49  ...             NaN             NaN             NaN   
1        99.98  ...             NaN             NaN             NaN   
2        59.99  ...             NaN             NaN             NaN   
3       419.98  ...             NaN             NaN             NaN   
4       199.99  ...             NaN             NaN             NaN   

  variantAsins/24 variantAsins/25 variantAsins/26 variantAsins/27  \
0             NaN             NaN             NaN             NaN   
1             NaN             NaN             NaN             NaN   
2             NaN             NaN             NaN             NaN   
3             NaN             NaN             NaN             NaN   
4             NaN             NaN             NaN             NaN   

  variantAsins/28 variantAsins/29                                   url  
0             NaN             NaN  https://www.amazon.com/dp/B0933G71SZ  
1             NaN             NaN  https://www.amazon.com/dp/B09KGB963V  
2             NaN             NaN  https://www.amazon.com/dp/B0721LJ2K4  
3             NaN             NaN  https://www.amazon.com/dp/B09GPYL7BJ  
4             NaN             NaN  https://www.amazon.com/dp/B084GB9YB4  

[5 rows x 54 columns]

In [ ]:
df.isnull().sum()

title                     0
seller                  500
seller/averageRating    500
seller/id               107
seller/name             107
seller/reviewsCount     500
seller/url              107
price                   500
price/currency            2
price/value               2
brand                     0
features/0                5
features/1               12
features/2               13
features/3               27
features/4               62
features/5              412
features/6              451
features/7              475
features/8              489
features/9              495
features/10             499
shippingPrice           500
variantAsins/0          379
variantAsins/1          379
variantAsins/2          414
variantAsins/3          435
variantAsins/4          462
variantAsins/5          472
variantAsins/6          478
variantAsins/7          485
variantAsins/8          488
variantAsins/9          489
variantAsins/10         491
variantAsins/11         492
variantAsins/12     

In [ ]:
df.shape

(500, 54)

In [ ]:
df.head()

title  seller  \
0              Apple TV Siri Remote (2nd Generation)     NaN   
1  Outdoor Bluetooth Speaker with Light, Gift for...     NaN   
2  Victrola Vintage 3-Speed Bluetooth Portable Su...     NaN   
3  Sonos Beam (Gen 2). The Compact Smart soundbar...     NaN   
4  Philips FX10 Bluetooth Stereo System for Home ...     NaN   

   seller/averageRating       seller/id seller/name  seller/reviewsCount  \
0                   NaN   ALAQLAKJ574UN        6ave                  NaN   
1                   NaN  A2J27EKX3JZ2SO    KuccHero                  NaN   
2                   NaN             NaN         NaN                  NaN   
3                   NaN   AFVUN7WVFH1YR       PetzX                  NaN   
4                   NaN   A6EGA15UEFYEQ   PHOTOTECH                  NaN   

                                          seller/url  price price/currency  \
0  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
1  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
2                                                NaN    NaN              $   
3  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
4  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   

   price/value  ... variantAsins/21 variantAsins/22 variantAsins/23  \
0        54.49  ...             NaN             NaN             NaN   
1        99.98  ...             NaN             NaN             NaN   
2        59.99  ...             NaN             NaN             NaN   
3       419.98  ...             NaN             NaN             NaN   
4       199.99  ...             NaN             NaN             NaN   

  variantAsins/24 variantAsins/25 variantAsins/26 variantAsins/27  \
0             NaN             NaN             NaN             NaN   
1             NaN             NaN             NaN             NaN   
2             NaN             NaN             NaN             NaN   
3             NaN             NaN             NaN             NaN   
4             NaN             NaN             NaN             NaN   

  variantAsins/28 variantAsins/29                                   url  
0             NaN             NaN  https://www.amazon.com/dp/B0933G71SZ  
1             NaN             NaN  https://www.amazon.com/dp/B09KGB963V  
2             NaN             NaN  https://www.amazon.com/dp/B0721LJ2K4  
3             NaN             NaN  https://www.amazon.com/dp/B09GPYL7BJ  
4             NaN             NaN  https://www.amazon.com/dp/B084GB9YB4  

[5 rows x 54 columns]

In [ ]:
column= ['seller/id', 'title', 'price/value']

In [ ]:
df[column].isnull().values.any()

True

In [ ]:
df.reset_index(drop=True,inplace=True)


In [ ]:
def get_imp_features(data):
    imp_features = []
    for i in range(0, df.shape[0]):
        imp_features.append("{} {} {}".format(data['seller/id'][i], data['title'][i], data['price/value'][i]))
    return imp_features


In [ ]:
df['imp_features']=get_imp_features(df)
df.head(2)

title  seller  \
0              Apple TV Siri Remote (2nd Generation)     NaN   
1  Outdoor Bluetooth Speaker with Light, Gift for...     NaN   

   seller/averageRating       seller/id seller/name  seller/reviewsCount  \
0                   NaN   ALAQLAKJ574UN        6ave                  NaN   
1                   NaN  A2J27EKX3JZ2SO    KuccHero                  NaN   

                                          seller/url  price price/currency  \
0  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
1  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   

   price/value  ... variantAsins/22 variantAsins/23 variantAsins/24  \
0        54.49  ...             NaN             NaN             NaN   
1        99.98  ...             NaN             NaN             NaN   

  variantAsins/25 variantAsins/26 variantAsins/27 variantAsins/28  \
0             NaN             NaN             NaN             NaN   
1             NaN             NaN             NaN             NaN   

  variantAsins/29                                   url  \
0             NaN  https://www.amazon.com/dp/B0933G71SZ   
1             NaN  https://www.amazon.com/dp/B09KGB963V   

                                        imp_features  
0  ALAQLAKJ574UN Apple TV Siri Remote (2nd Genera...  
1  A2J27EKX3JZ2SO Outdoor Bluetooth Speaker with ...  

[2 rows x 55 columns]

In [ ]:
#text to matrix
cm=CountVectorizer().fit_transform(df['imp_features'])

In [ ]:
#get cosin similarity
cs=cosine_similarity(cm)
print(cs)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.1628224  ... 0.03062819 0.08282364 0.17400444]
 [0.         0.1628224  1.         ... 0.20446521 0.29488391 0.19360077]
 ...
 [0.         0.03062819 0.20446521 ... 1.         0.17334381 0.03641785]
 [0.         0.08282364 0.29488391 ... 0.17334381 1.         0.09847982]
 [0.         0.17400444 0.19360077 ... 0.03641785 0.09847982 1.        ]]


In [ ]:
cs.shape

(500, 500)

In [ ]:
df['product_id']=range(1,len(df) + 1)


In [ ]:
title='Apple TV Siri Remote (2nd Generation)'
movies_id=df[df.title == title]['product_id'].values[0]


In [ ]:
df.head(3)

title  seller  \
0              Apple TV Siri Remote (2nd Generation)     NaN   
1  Outdoor Bluetooth Speaker with Light, Gift for...     NaN   
2  Victrola Vintage 3-Speed Bluetooth Portable Su...     NaN   

   seller/averageRating       seller/id seller/name  seller/reviewsCount  \
0                   NaN   ALAQLAKJ574UN        6ave                  NaN   
1                   NaN  A2J27EKX3JZ2SO    KuccHero                  NaN   
2                   NaN             NaN         NaN                  NaN   

                                          seller/url  price price/currency  \
0  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
1  /gp/help/seller/at-a-glance.html/ref=dp_mercha...    NaN              $   
2                                                NaN    NaN              $   

   price/value  ... variantAsins/23 variantAsins/24 variantAsins/25  \
0        54.49  ...             NaN             NaN             NaN   
1        99.98  ...             NaN             NaN             NaN   
2        59.99  ...             NaN             NaN             NaN   

  variantAsins/26 variantAsins/27 variantAsins/28 variantAsins/29  \
0             NaN             NaN             NaN             NaN   
1             NaN             NaN             NaN             NaN   
2             NaN             NaN             NaN             NaN   

                                    url  \
0  https://www.amazon.com/dp/B0933G71SZ   
1  https://www.amazon.com/dp/B09KGB963V   
2  https://www.amazon.com/dp/B0721LJ2K4   

                                        imp_features product_id  
0  ALAQLAKJ574UN Apple TV Siri Remote (2nd Genera...          1  
1  A2J27EKX3JZ2SO Outdoor Bluetooth Speaker with ...          2  
2  nan Victrola Vintage 3-Speed Bluetooth Portabl...          3  

[3 rows x 56 columns]

In [ ]:
scores=list(enumerate(cs[movies_id]))

In [ ]:
sorted_scores=sorted(scores,key=lambda x:x[1],reverse=True)
sorted_scores=sorted_scores[1:]

In [ ]:
print(sorted_scores)

[(288, 0.6161953991557161), (277, 0.5356715840055801), (289, 0.42879472428218224), (323, 0.39652233878659904), (296, 0.3836828684656209), (49, 0.3706728665329306), (458, 0.33377250787601287), (267, 0.3214029504033481), (329, 0.30809769957785804), (324, 0.2996672211954121), (426, 0.29614369785098454), (184, 0.2946193712030691), (273, 0.2903800225416501), (52, 0.2869095208785022), (493, 0.28242289127970327), (96, 0.2824228912797032), (32, 0.2815462531857365), (4, 0.2726392706363988), (495, 0.2656266012454299), (12, 0.2650794809915339), (283, 0.2650794809915339), (76, 0.2602896031476768), (63, 0.25898488514140616), (357, 0.2524467210539465), (59, 0.24987801902176973), (131, 0.24620505620053532), (264, 0.24467726152216662), (397, 0.24467726152216662), (401, 0.24445060351935236), (321, 0.23855936180684897), (99, 0.23544080467400558), (37, 0.2342606428329091), (80, 0.23107327468339353), (35, 0.22795136315904269), (310, 0.22726620572357106), (169, 0.2254174086668581), (313, 0.2231518495721684

In [ ]:
j=0
print('top 5 similar products')
for item in sorted_scores:
  product_title=df[df.product_id == item[0]]['title'].values[0]
  print(j+1,product_title)
  j=j+1
  if j>5:
    break

top 5 similar products
1 Optage Audio Mini Record Holder, 35 LP Solid Walnut Vinyl Record Storage, Vinyl Holder for Record Display, Now Playing Vinyl Record Stand, Vinyl Record Holder, Record Stand, Vinyl Storage, Vinyl Stand
2 SAMSUNG HW-N300 2-Channel TV Mate Soundbar, Bluetooth Wireless, Built-in USB Port, Surround Sound Expansion, Booming Bass with a Built-in Woofer, Audio Remote App
3 2 Pack Outdoor Bluetooth Speakers, IPX5 Waterproof Wireless Speaker with LED Flame Light Portable Speaker Bluetooth 5.0, Torch Atmosphere Lantern for Patio Yard Pool Party Decor, Gift for Women Men
4 Marvour for Hisense-TV-Remote Compatible with All Hisense 4K LED HD UHD Smart TVs
5 2021 Model BN59-01385A Replacement Remote Control for Samsung Smart TVs Compatible with Neo QLED, The Frame and Crystal UHD Series
6 Klipsch CDT-5650-C II In-Ceiling Speaker - White (Each)
